/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.compass;

import android.app.Activity;
import android.graphics.Color;
import android.view.View;
import android.widget.LinearLayout;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.TiDimension;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;


// This proxy can be created by calling TiCompass.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = TiCompassModule.class)
public class StageProxy extends TiViewProxy {
    // Standard Debugging variables
    private static final String LCAT = "ExampleProxy";
    private static final boolean DBG = TiConfig.LOGD;
    TiUIView view;

    // Constructor
    public StageProxy() {
        super();
    }

    protected ExampleView getView() {
        return (ExampleView) getOrCreateView();
    }

    @Override
    public TiUIView createView(Activity activity) {
        view = new ExampleView(this);
        view.getLayoutParams().autoFillsHeight = true;
        view.getLayoutParams().autoFillsWidth = true;
        return view;
    }

    // Handle creation options
    @Override
    public void handleCreationDict(KrollDict options) {
        super.handleCreationDict(options);

        if (options.containsKey("message")) {
            Log.d(LCAT, "example created with message: " + options.get("message"));
        }
    }

    @Kroll.method
    public void createInfoBox(KrollDict kd) {
        // add a view
        CustomViewProxy customViewProxy = new CustomViewProxy();
        TiUIView customView = customViewProxy.getOrCreateView();
        customView.getLayoutParams().optionLeft = TiConvert.toTiDimension("100",100);
        customView.getLayoutParams().optionTop = TiConvert.toTiDimension("100",100);
        customView.getLayoutParams().optionWidth = TiConvert.toTiDimension("100",100);
        customView.getLayoutParams().optionHeight = TiConvert.toTiDimension("100",100);
        view.add(customView);
    }

    private class ExampleView extends TiUIView {
        public ExampleView(TiViewProxy proxy) {
            super(proxy);
            LayoutArrangement arrangement = LayoutArrangement.DEFAULT;
            setNativeView(new TiCompositeLayout(proxy.getActivity(), arrangement));
        }

        @Override
        public void processProperties(KrollDict d) {
            super.processProperties(d);
        }
    }
}
